# Generated by Django 4.2.1 on 2023-05-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_basket_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='created date/time')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='banner image')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_product', to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
