# Generated by Django 4.2.1 on 2023-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_orderproduct_product_orderproduct_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycountries',
            name='delivery_price',
            field=models.FloatField(blank=True, null=True, verbose_name='deliver price'),
        ),
    ]
