# Generated by Django 4.2.1 on 2023-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deliverycountries_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(null=True, verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='total quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='total price'),
        ),
    ]
