# Generated by Django 4.2.1 on 2023-05-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('pcs', 'pieces')], max_length=20, null=True, unique=True, verbose_name='product type'),
        ),
    ]
